### Registrar Usuario
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "identificacion":"1850509249",
    "primer_nombre":"Cristina",
    "segundo_nombre":"Estefania",
    "primer_apellido":"Chacha",
    "segundo_apellido":"Machado",
    "correo":"cristina@edu.com",
    "password":"123456",
    "telefono":"0988508826",
    "direccion":"Calle 123"
}

### Iniciar Sesion
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "correo":"cristina@edu.com",
    "password":"123456"
}

### Perfil
GET http://localhost:3000/api/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsImNvcnJlbyI6ImNyaXN0aW5hQGVkdS5jb20iLCJyb2wiOiJhZG1pbmlzdHJhZG9yIiwicHJpbWVyX25vbWJyZSI6IkNyaXN0aW5hIiwicHJpbWVyX2FwZWxsaWRvIjoiQ2hhY2hhIiwiaWF0IjoxNzMyNDA0MDQ5LCJleHAiOjE3MzI0OTA0NDl9.21YnC0ZYvATHzuxbkxwmdK5lcCwYDECJLWdix-dzGR4