### Registrar Usuario
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "identificacion":"0504375734",
    "primer_nombre":"Juan",
    "segundo_nombre":"Carlos",
    "primer_apellido":"Perez",
    "segundo_apellido":"Gomez",
    "correo":"adfasdf@gg.com",
    "password":"123456",
    "telefono":"0988850126",
    "direccion":"Calle 123"
}

### Iniciar Sesion
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "correo":"adfasdf@gg.com",
    "password":"123456"
}

### Perfil
GET http://localhost:3000/api/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb3JyZW8iOiJhZGZhc2RmQGdnLmNvbSIsInJvbCI6InVzdWFyaW9fbm9ybWFsIiwicHJpbWVyX25vbWJyZSI6Ikp1YW4iLCJwcmltZXJfYXBlbGxpZG8iOiJQZXJleiIsImlhdCI6MTczMjE0NDM1OSwiZXhwIjoxNzMyMjMwNzU5fQ._gtoamF9GVoos2NO1vcg0hwuOljt7T9NEuaKfYFoakg