### Registrar Usuario
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "identificacion":"0504375734",
    "primer_nombre":"Juan",
    "segundo_nombre":"Carlos",
    "primer_apellido":"Perez",
    "segundo_apellido":"Gomez",
    "correo":"adfasdf@gg.com",
    "password":"123456",
    "telefono":"0988850126",
    "direccion":"Calle 123"
}

### Iniciar Sesion
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "correo":"adfasdf@gg.com",
    "password":"123456"
}