###Obtener todas las reservas
GET http://localhost:3000/api/reserva

###Crear una reserva
POST http://localhost:3000/api/reserva
Content-Type: application/json

{
    "usuario_id": 17,
    "asiento_id": 51,
    "frecuencia_id": 8,
    "boleto_id": 1,
    "nombre_pasajero": "John Doe",
    "identificacion_pasajero": "123456789",
    "fecha_viaje": "2023-05-15",
    "hora_viaje": "10:00:00",
    "precio": 100,
    "destino_reserva": "New York"
}